#PBS -N test_KTH
#PBS -j oe
#PBS -l walltime=3:00:00:00
#PBS -l nodes=1:ppn=8:gpus=1:lgn
#PBS -S /bin/bash
#PBS -m abe
#PBS -M lukunyi@umich.edu
#PBS -o /z/home/lukunyi/Super-SloMo/pbs_scripts/logs1

# Print some cluster info
date
echo "allocated node"; cat $PBS_NODEFILE
echo "GPU allocated"; cat $PBS_GPUFILE

# Set up the project environment
cd /z/home/lukunyi/Super-SloMo
source /z/home/lukunyi/.bashrc
conda activate /z/home/lukunyi/slomo_env

python val.py